In [1]:
import logging
logging.getLogger().setLevel(logging.CRITICAL)
!pip install pylabel > /dev/null

WARNING: Error parsing requirements for fastjsonschema: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/fastjsonschema-2.16.3.dist-info/METADATA'
WARNING: Error parsing requirements for torch: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/torch-1.9.0.dist-info/METADATA'

In [2]:
from pylabel import importer

In [24]:
#Specify path to the coco.json file
path_to_annotations = "/home/jupyter/dacon/data/sample/annotations/updated_data.json"
#Specify the path to the images (if they are in a different folder than the annotations)
path_to_images = "/home/jupyter/dacon/data/sample/train"

#Import the dataset into the pylable schema 
dataset = importer.ImportCoco(path_to_annotations, path_to_images=path_to_images, name="coco")
dataset.df.head(40)

,img_folder,img_filename,img_path,img_id,img_width,img_height,img_depth,ann_segmented,ann_bbox_xmin,ann_bbox_ymin,...,ann_segmentation,ann_iscrowd,ann_pose,ann_truncated,ann_difficult,cat_id,cat_name,cat_supercategory,split,annotated
id,,,,,,,,,,,,,,,,,,,,,
0,/home/jupyter/dacon/data/sample/train,syn_00006.png,,0,1920,1040,,,1112.0,315.0,...,,0,,,,0,kia_sorrento_suv_2015_2019,,,1
1,/home/jupyter/dacon/data/sample/train,syn_00006.png,,0,1920,1040,,,725.0,316.0,...,,0,,,,1,renault_xm3_suv_2020_,,,1
2,/home/jupyter/dacon/data/sample/train,syn_00006.png,,0,1920,1040,,,331.0,290.0,...,,0,,,,2,chevrolet_malibu_sedan_2017_2019,,,1
3,/home/jupyter/dacon/data/sample/train,syn_00003.png,,1,1920,1040,,,1118.0,439.0,...,,0,,,,3,hyundai_sonata_sedan_2019_2020,,,1
4,/home/jupyter/dacon/data/sample/train,syn_00003.png,,1,1920,1040,,,614.0,176.0,...,,0,,,,4,hyundai_sonata_sedan_2004_2009,,,1
5,/home/jupyter/dacon/data/sample/train,syn_00001.png,,2,1920,1040,,,1000.0,98.0,...,,0,,,,5,kia_carnival_van_2015_2020,,,1
6,/home/jupyter/dacon/data/sample/train,syn_00001.png,,2,1920,1040,,,678.0,175.0,...,,0,,,,6,hyundai_sonata_sedan_2010_2014,,,1
7,/home/jupyter/dacon/data/sample/train,syn_00001.png,,2,1920,1040,,,427.0,560.0,...,,0,,,,1,renault_xm3_suv_2020_,,,1
8,/home/jupyter/dacon/data/sample/train,syn_00005.png,,3,1920,1040,,,1115.0,365.0,...,,0,,,,6,hyundai_sonata_sedan_2010_2014,,,1
9,/home/jupyter/dacon/data/sample/train,syn_00005.png,,3,1920,1040,,,672.0,195.0,...,,0,,,,7,chevrolet_trailblazer_suv_2021_,,,1
10,/home/jupyter/dacon/data/sample/train,syn_00005.png,,3,1920,1040,,,332.0,292.0,...,,0,,,,8,kia_k7_sedan_2016_2020,,,1
11,/home/jupyter/dacon/data/sample/train,syn_00009.png,,4,1920,1040,,,1075.0,357.0,...,,0,,,,9,kia_k5_sedan_2010_2015,,,1
12,/home/jupyter/dacon/data/sample/train,syn_00009.png,,4,1920,1040,,,730.0,403.0,...,,0,,,,10,ssangyong_korando_suv_2019_2020,,,1
13,/home/jupyter/dacon/data/sample/train,syn_00009.png,,4,1920,1040,,,314.0,387.0,...,,0,,,,11,kia_carnival_van_2021_,,,1
14,/home/jupyter/dacon/data/sample/train,syn_00010.png,,5,1920,1040,,,1099.0,257.0,...,,0,,,,12,kia_ray_hatchback_2012_2017,,,1
15,/home/jupyter/dacon/data/sample/train,syn_00010.png,,5,1920,1040,,,682.0,178.0,...,,0,,,,13,kia_soul_suv_2014_2018,,,1
16,/home/jupyter/dacon/data/sample/train,syn_00007.png,,6,1920,1040,,,1090.0,373.0,...,,0,,,,14,genesis_g80_sedan_2016_2020,,,1
17,/home/jupyter/dacon/data/sample/train,syn_00007.png,,6,1920,1040,,,311.0,281.0,...,,0,,,,10,ssangyong_korando_suv_2019_2020,,,1
18,/home/jupyter/dacon/data/sample/train,syn_00004.png,,7,1920,1040,,,1002.0,124.0,...,,0,,,,15,hyundai_grandstarex_van_2018_2020,,,1
19,/home/jupyter/dacon/data/sample/train,syn_00004.png,,7,1920,1040,,,691.0,284.0,...,,0,,,,4,hyundai_sonata_sedan_2004_2009,,,1
20,/home/jupyter/dacon/data/sample/train,syn_00004.png,,7,1920,1040,,,332.0,304.0,...,,0,,,,16,chevrolet_spark_hatchback_2016_2021,,,1
21,/home/jupyter/dacon/data/sample/train,syn_00000.png,,8,1920,1040,,,1037.0,209.0,...,,0,,,,17,hyundai_avante_sedan_2020_,,,1
22,/home/jupyter/dacon/data/sample/train,syn_00000.png,,8,1920,1040,,,804.0,425.0,...,,0,,,,0,kia_sorrento_suv_2015_2019,,,1
23,/home/jupyter/dacon/data/sample/train,syn_00000.png,,8,1920,1040,,,330.0,250.0,...,,0,,,,18,hyundai_ioniq_hatchback_2016_2019,,,1
24,/home/jupyter/dacon/data/sample/train,syn_00008.png,,10,1920,1040,,,1119.0,352.0,...,,0,,,,19,chevrolet_trax_suv_2017_2019,,,1
25,/home/jupyter/dacon/data/sample/train,syn_00008.png,,10,1920,1040,,,333.0,394.0,...,,0,,,,20,genesis_g80_sedan_2021_,,,1
26,/home/jupyter/dacon/data/sample/train,syn_00012.png,,11,1920,1040,,,1087.0,384.0,...,,0,,,,21,kia_morning_hatchback_2011_2016,,,1
27,/home/jupyter/dacon/data/sample/train,syn_00012.png,,11,1920,1040,,,660.0,283.0,...,,0,,,,10,ssangyong_korando_suv_2019_2020,,,1
28,/home/jupyter/dacon/data/sample/train,syn_00012.png,,11,1920,1040,,,308.0,381.0,...,,0,,,,22,kia_sorrento_suv_2020_,,,1
29,/home/jupyter/dacon/data/sample/train,syn_00002.png,,12,1920,1040,,,1108.0,313.0,...,,0,,,,19,chevrolet_trax_suv_2017_2019,,,1
30,/home/jupyter/dacon/data/sample/train,syn_00002.png,,12,1920,1040,,,705.0,269.0,...,,0,,,,16,chevrolet_spark_hatchback_2016_2021,,,1
31,/home/jupyter/dacon/data/sample/train,syn_00011.png,,13,1920,1040,,,1165.0,396.0,...,,0,,,,23,ssangyong_tivoli_suv_2016_2020,,,1
32,/home/jupyter/dacon/data/sample/train,syn_00011.png,,13,1920,1040,,,792.0,469.0,...,,0,,,,24,kia_k5_sedan_2020_,,,1
33,/home/jupyter/dacon/data/sample/train,syn_00011.png,,13,1920,1040,,,359.0,377.0,...,,0,,,,18,hyundai_ioniq_hatchback_2016_2019,,,1

In [9]:
dataset.export.ExportToVoc(output_path="/home/jupyter/dacon/data/sample/annotations/")

Exporting VOC files...: 100%|██████████| 13/13 [00:00<00:00, 196.76it/s]

['/home/jupyter/dacon/data/sample/annotations/syn_00005.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00002.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00003.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00010.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00004.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00009.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00011.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00006.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00007.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00000.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00008.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00001.xml',
 '/home/jupyter/dacon/data/sample/annotations/syn_00012.xml']

In [ ]:
from IPython.display import Image, display
display(dataset.visualize.ShowBoundingBoxes("syn_00000.png"))